[package]
name = "walletcore-crypto-bindgen"
version = "0.1.0"
edition = "2021"

[lib]
name = "walletcore_crypto_bindgen"
crate-type = ["staticlib"] # Creates static lib

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
